### ISSUE TITLE
Add check if snakemake is installed

### ISSUE THREAD

**Issue by HauHe** [KTH-dESA/OSeMOSYS_step#44]
The error one get's if snakemake is not installed doesn't indicate that it is related to the missing installation. A upfront check for the installation might be useful

**Comment by trevorb1** [comment]
Maybe we can just include a conda environment file; something along the lines of: 

```yaml 
name: step

channels:
 - bioconda
 - conda-forge
 
dependencies:
 - python>=3.8
 - pip
 - pandas
 - snakemake-minimal
 - pip:
      - otoole>=1.0.0
```
